name: Build CPU-Only Whisper DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Unity with License
      - name: Activate Unity License
        uses: webbertakken/unity-actions/activate@v2
        with:
          unityVersion: 2022.3.17f1 # Replace with your Unity version
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # Set up CMake
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22'

      # Configure CMake
      - name: Configure CMake
        run: cmake -B build -A x64 -DUSE_CUDA=OFF

      # Build the project
      - name: Build with CMake
        run: cmake --build build --config Release

      # Archive build outputs
      - name: Upload Release DLL
        uses: actions/upload-artifact@v3
        with:
          name: whisper-cpu-dll
          path: build/Release/
