name: Build CPU-Only Whisper DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up CMake
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22'

      # Set up MSVC compiler
      - name: Setup MSVC
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

      # Configure CMake
      - name: Configure CMake
        run: cmake -B build -A x64 -DUSE_CUDA=OFF

      # Build the project
      - name: Build with CMake
        run: cmake --build build --config Release

      # Archive build outputs
      - name: Upload Release DLL
        uses: actions/upload-artifact@v3
        with:
          name: whisper-cpu-dll
          path: build/Release/
